import express, { Request, Response } from 'express';
import { Octokit } from '@octokit/rest';
import { runWeeklyResearch, searchTavily } from './tavily.js';
import { initResearcherMemory, storeFinding, searchFindings, StoredFinding } from './qdrant-researcher.js';
import { ResearchFinding, RunResponse, TavilyResult } from './types.js';
import { callLLM } from './llm-router.js';

const app = express();
app.use(express.json());

const PORT = process.env.PORT ?? '8080';

const GITHUB_OWNER = process.env.GITHUB_OWNER ?? '';
const GITHUB_REPO = process.env.GITHUB_REPO ?? '';

function sanitiseForLLM(text: string): string {
  // Remove unpaired Unicode surrogates that cause Anthropic API
  // to reject the request body as invalid JSON (HTTP 400)
  // Tavily snippets frequently contain emoji with broken surrogate pairs
  return text
    .replace(/[\uD800-\uDBFF](?![\uDC00-\uDFFF])/g, '')
    .replace(/(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/g, '')
    .replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g, '')
    .trim();
}
function buildMarkdownReport(
  results: Map<string, TavilyResult[]>,
  timestamp: string
): string {
  const lines: string[] = [
    `# OpenClaw Weekly Research Report`,
    ``,
    `**Generated:** ${timestamp}`,
    `**Bot:** openclaw-researcher`,
    ``,
    `---`,
    ``,
  ];

  for (const [query, findings] of results.entries()) {
    lines.push(`## Query: "${query}"`);
    lines.push('');

    if (findings.length === 0) {
      lines.push('_No results found for this query._');
      lines.push('');
      continue;
    }

    const top3 = findings.slice(0, 3);
    for (const finding of top3) {
      lines.push(`### ${finding.title}`);
      lines.push(`**URL:** ${finding.url}`);
      lines.push(`**Relevance:** ${finding.score.toFixed(3)}`);
      lines.push('');
      lines.push(finding.content.slice(0, 300));
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  lines.push('_Review and close this PR when done. No merge required._');
  return lines.join('\n');
}

async function openReportPR(
  markdown: string,
  timestamp: string
): Promise<string> {
  const token = process.env.GITHUB_PAT ?? '';
  if (!token) throw new Error('GITHUB_PAT not set');

  const octokit = new Octokit({ auth: token });
  const branch = `research/weekly-${timestamp.replace(/[:.]/g, '-')}`;

  const { data: mainRef } = await octokit.git.getRef({
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO,
    ref: 'heads/main',
  });
  const mainSha = mainRef.object.sha;

  await octokit.git.createRef({
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO,
    ref: `refs/heads/${branch}`,
    sha: mainSha,
  });

  const path = `research/report-${timestamp.slice(0, 10)}.md`;
  await octokit.repos.createOrUpdateFileContents({
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO,
    path,
    message: `research: weekly report ${timestamp.slice(0, 10)}`,
    content: Buffer.from(markdown, 'utf-8').toString('base64'),
    branch,
  });

  const { data: pr } = await octokit.pulls.create({
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO,
    title: `[Research] Weekly Report — ${timestamp.slice(0, 10)}`,
    body: `Weekly research report generated by openclaw-researcher.\n\nReview findings below. Close this PR when done — no merge required.`,
    head: branch,
    base: 'main',
  });

  return pr.html_url;
}

async function synthesiseFindings(
  findings: StoredFinding[],
  topic: string
): Promise<string> {
  console.log(`[Researcher] synthesiseFindings: topic="${topic.slice(0, 60)}" findings=${findings.length}`);

  if (findings.length === 0) {
    console.log('[Researcher] synthesiseFindings: no findings to synthesise');
    return 'No relevant findings available for this topic.';
  }

  // AFTER
const findingsText = findings
  .map((f, i) => `[${i + 1}] ${sanitiseForLLM(f.title)}\nURL: ${f.url}\nSnippet: ${sanitiseForLLM(f.snippet)}`)
  .join('\n\n');

  const prompt = `You are a research analyst synthesising findings for the OpenClaw ecosystem.

Topic: ${topic}

Findings:
${findingsText}

Write a concise synthesis (3-5 sentences) that:
- Identifies the most important pattern or insight across these findings
- Notes any contradictions or gaps
- States what is most actionable for an AI engineering team

Return only the synthesis text. No headers, no bullet points, no preamble.`;

  try {
    const response = await callLLM({
      task: 'research_synthesis',
      prompt,
      systemPrompt: 'You are a research analyst. Return only the synthesis paragraph, nothing else.',
      maxTokens: 300,
    });
    console.log(`[Researcher] synthesiseFindings: synthesis complete via ${response.provider} using ${response.model}`);
    return response.text;
  } catch (err: unknown) {
    const e = err instanceof Error ? err : new Error(String(err));
    console.warn(`[Researcher] synthesiseFindings: LLM failed — ${e.message}`);
    return 'Synthesis unavailable — LLM call failed.';
  }
}

app.get('/health', (_req: Request, res: Response) => {
  res.json({ status: 'ok', bot: 'openclaw-researcher', version: '1.2.2' });
});

app.post('/run', async (_req: Request, res: Response) => {
  console.log('[Researcher] /run triggered -- starting weekly research');

  res.status(202).json({
    status: 'ok',
    message: 'Research run started -- check logs for progress',
  });

  const timestamp = new Date().toISOString();
  let findingsStored = 0;
  const allFindings: StoredFinding[] = [];

  try {
    const results = await runWeeklyResearch();

    for (const [query, findings] of results.entries()) {
      for (const finding of findings.slice(0, 3)) {
        const stored = await storeFinding({
          timestamp,
          query,
          title: finding.title,
          url: finding.url,
          content: finding.content,
          relevanceScore: finding.score,
          bot: 'researcher',
        } as ResearchFinding);
        if (stored) {
          findingsStored++;
          allFindings.push({
            title: finding.title,
            url: finding.url,
            snippet: finding.content.slice(0, 300),
            publishedAt: timestamp,
            relevanceScore: finding.score,
          });
        }
      }
    }

    console.log(`[Researcher] Stored ${findingsStored} new findings`);

    if (allFindings.length > 0) {
      const synthesis = await synthesiseFindings(allFindings.slice(0, 5), 'weekly AI engineering research');
      console.log(`[Researcher] Weekly synthesis: ${synthesis.slice(0, 200)}`);
    }

    const markdown = buildMarkdownReport(results, timestamp);
    const prUrl = await openReportPR(markdown, timestamp);
    console.log(`[Researcher] PR opened: ${prUrl}`);
    console.log(`[Researcher] Run complete -- ${findingsStored} findings stored`);

  } catch (err: unknown) {
    const e = err instanceof Error ? err : new Error(String(err));
    console.error(`[Researcher] Run failed: ${e.message}`);
  }
});

app.post('/research', async (req: Request, res: Response) => {
  console.log('[Researcher] /research triggered');

  const body = req.body as Record<string, unknown>;
  const topic = typeof body['topic'] === 'string' ? body['topic'] : '';
  const maxAge = typeof body['maxAge'] === 'number' ? body['maxAge'] : 30;
  const limit = typeof body['limit'] === 'number' ? body['limit'] : 5;

  if (!topic) {
    res.status(400).json({ error: 'topic is required' });
    return;
  }

  console.log(`[Researcher] /research: topic="${topic.slice(0, 60)}" maxAge=${maxAge} limit=${limit}`);

  try {
    let findings = await searchFindings(topic, limit, maxAge);
    const fromCache = findings.length > 0;

    console.log(`[Researcher] /research: found ${findings.length} cached findings fromCache=${fromCache}`);

    if (findings.length === 0) {
      console.log(`[Researcher] /research: cache empty -- calling Tavily live for "${topic.slice(0, 60)}"`);
      try {
        const liveResults = await searchTavily(topic);
        const timestamp = new Date().toISOString();
        for (const result of liveResults.slice(0, limit)) {
          await storeFinding({
            timestamp,
            query: topic,
            title: result.title,
            url: result.url,
            content: result.content,
            relevanceScore: result.score,
            bot: 'researcher',
          } as ResearchFinding);
        }
        findings = await searchFindings(topic, limit, maxAge);
        console.log(`[Researcher] /research: Tavily returned ${liveResults.length} results, now have ${findings.length} findings`);
      } catch (tavilyErr: unknown) {
        const te = tavilyErr instanceof Error ? tavilyErr : new Error(String(tavilyErr));
        console.error(`[Researcher] /research: Tavily fallback failed -- ${te.message}`);
      }
    }

    const synthesis = await synthesiseFindings(findings, topic);

    res.json({
      findings,
      fromCache,
      synthesis,
    });

  } catch (err: unknown) {
    const e = err instanceof Error ? err : new Error(String(err));
    console.error(`[Researcher] /research failed: ${e.message}`);
    res.status(500).json({ error: 'Research lookup failed', detail: e.message });
  }
});

app.listen(parseInt(PORT), '0.0.0.0', async () => {
  console.log('[Researcher] Boot confirmed -- openclaw-researcher v1.2.1');
  console.log('[Researcher] LLM router loaded -- task: research_synthesis');
  console.log(`[Researcher] Health server on port ${PORT}`);

  try {
    await initResearcherMemory();
  } catch (err: unknown) {
    const e = err instanceof Error ? err : new Error(String(err));
    console.error(`[Researcher] Memory init failed: ${e.message}`);
  }
});
