import express, { Request, Response } from 'express';
import { Octokit } from '@octokit/rest';
import { runWeeklyResearch } from './tavily.js';
import { initResearcherMemory, storeFinding } from './qdrant-researcher.js';
import { ResearchFinding, RunResponse, TavilyResult } from './types.js';
import { callLLM } from './llm-router.js';

const app = express();
app.use(express.json());

const PORT = process.env.PORT ?? '8080';

const GITHUB_OWNER = process.env.GITHUB_OWNER ?? '';
const GITHUB_REPO = process.env.GITHUB_REPO ?? '';

function buildMarkdownReport(
  results: Map<string, TavilyResult[]>,
  timestamp: string
): string {
  const lines: string[] = [
    `# OpenClaw Weekly Research Report`,
    ``,
    `**Generated:** ${timestamp}`,
    `**Bot:** openclaw-researcher`,
    ``,
    `---`,
    ``,
  ];

  for (const [query, findings] of results.entries()) {
    lines.push(`## Query: "${query}"`);
    lines.push('');

    if (findings.length === 0) {
      lines.push('_No results found for this query._');
      lines.push('');
      continue;
    }

    const top3 = findings.slice(0, 3);
    for (const finding of top3) {
      lines.push(`### ${finding.title}`);
      lines.push(`**URL:** ${finding.url}`);
      lines.push(`**Relevance:** ${finding.score.toFixed(3)}`);
      lines.push('');
      lines.push(finding.content.slice(0, 300));
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  lines.push('_Review and close this PR when done. No merge required._');
  return lines.join('\n');
}

async function openReportPR(
  markdown: string,
  timestamp: string
): Promise<string> {
  const token = process.env.GITHUB_PAT ?? '';
  if (!token) throw new Error('GITHUB_PAT not set');

  const octokit = new Octokit({ auth: token });
  const branch = `research/weekly-${timestamp.replace(/[:.]/g, '-')}`;

  const { data: mainRef } = await octokit.git.getRef({
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO,
    ref: 'heads/main',
  });
  const mainSha = mainRef.object.sha;

  await octokit.git.createRef({
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO,
    ref: `refs/heads/${branch}`,
    sha: mainSha,
  });

  const path = `research/report-${timestamp.slice(0, 10)}.md`;
  await octokit.repos.createOrUpdateFileContents({
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO,
    path,
    message: `research: weekly report ${timestamp.slice(0, 10)}`,
    content: Buffer.from(markdown, 'utf-8').toString('base64'),
    branch,
  });

  const { data: pr } = await octokit.pulls.create({
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO,
    title: `[Research] Weekly Report — ${timestamp.slice(0, 10)}`,
    body: `Weekly research report generated by openclaw-researcher.\n\nReview findings below. Close this PR when done — no merge required.`,
    head: branch,
    base: 'main',
  });

  return pr.html_url;
}

app.get('/health', (_req: Request, res: Response) => {
  res.json({ status: 'ok', bot: 'openclaw-researcher', version: '1.1.0' });
});

app.post('/run', async (_req: Request, res: Response) => {
  console.log('[Researcher] /run triggered — starting weekly research');

  res.status(202).json({
    status: 'ok',
    message: 'Research run started — check logs for progress',
  });

  const timestamp = new Date().toISOString();
  let findingsStored = 0;

  try {
    const results = await runWeeklyResearch();

    for (const [query, findings] of results.entries()) {
      for (const finding of findings.slice(0, 3)) {
        const stored = await storeFinding({
          timestamp,
          query,
          title: finding.title,
          url: finding.url,
          content: finding.content,
          relevanceScore: finding.score,
          bot: 'researcher',
        } as ResearchFinding);
        if (stored) findingsStored++;
      }
    }

    console.log(`[Researcher] Stored ${findingsStored} new findings`);

    const markdown = buildMarkdownReport(results, timestamp);
    const prUrl = await openReportPR(markdown, timestamp);
    console.log(`[Researcher] PR opened: ${prUrl}`);
    console.log(`[Researcher] Run complete — ${findingsStored} findings stored`);

  } catch (err: unknown) {
    const e = err instanceof Error ? err : new Error(String(err));
    console.error(`[Researcher] Run failed: ${e.message}`);
  }
});

app.listen(parseInt(PORT), '0.0.0.0', async () => {
  console.log('[Researcher] Boot confirmed — openclaw-researcher v1.1.0');
  console.log('[Researcher] LLM router loaded — task: research_synthesis');
  console.log(`[Researcher] Health server on port ${PORT}`);

  try {
    await initResearcherMemory();
  } catch (err: unknown) {
    const e = err instanceof Error ? err : new Error(String(err));
    console.error(`[Researcher] Memory init failed: ${e.message}`);
  }
});

void callLLM;
